// frontend/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { PdfServiceService } from '../service/pdf-service.service';
import { FormGroup, FormControl, FormBuilder, Validators } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  loginForm = new FormGroup({
  
    email: new FormControl(),
    password: new FormControl(),


  });

  constructor(private service:PdfServiceService, private router:Router) { }

  ngOnInit(): void {
  }

  onlogin(){


    if(this.loginForm.value.password != '' || this.loginForm.value.email != '' ){
      console.log('success')
      this.service.onLogin(this.loginForm.value).subscribe((data:any)=>{

      
          sessionStorage.setItem('token',data.token)
          console.log('success')
          this.router.navigateByUrl('/landing');
        
    
        
      }),(error:HttpErrorResponse)=>{
       
        console.log(error)
       
      }
     

    }else{
      console.log('fill all fields')
    }


  }

  }



<div class="w-full min-h-screen">
    <div class="logo">
        <img class="logo" src="../../assets/2.png" alt="">
    </div> 

    <div class="w-full max-w-xs mx-6">
        <form class="form shadow-md rounded px-8 pt-6 pb-8 mb-4"[formGroup]="loginForm" (ngSubmit)="onlogin()">
          <div class="mb-4">
            <label class="block text-[white] text-sm font-bold mb-2 mt-5" for="username">
                <i class="fi fi-sr-user"></i> &nbsp; Username
            </label>
            <input formControlName="email"  class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="email" type="text" placeholder="Username">
          </div>
          <div class="mb-6">
            <label class="block text-[white] text-sm font-bold mb-2" for="password">
                <i class="fi fi-sr-lock"></i> &nbsp; Password
            </label>
            <input formControlName="password" class="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" id="password" type="password" placeholder="******************">
            <!-- <p class="text-red-500 text-xs italic">Please choose a password.</p> -->
          </div>
          <div class="flex items-center justify-between">
            <button class="bg-[#3fba3e] hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
              Sign In
            </button>
          
            <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="#" [routerLink]="['/register']" routerLinkActive="router-link-active">
              Sign up?
            </a>

          </div>
        </form>
        <p class="text-center text-gray-500 text-xs mt-16">
          &copy;2020 PDF Scanner. All rights reserved.s
        </p>
      </div>

</div>

// front_end/src/views/login.vue
<!-- eslint-disable vue/multi-word-component-names -->
<template class="align-center">
 
 <div class="w-full h-auto mb-5">
    <RouterLink class="logo1"  to="/">
        <img  src="../assets/2.png" alt="">
    </RouterLink> 

    <form class="px-8 py-8 ">
     
    <div class="mb-4">
            <label class="block text-[white]  text-sm font-bold mb-2 mt-5" for="username">
                <i class="fi fi-sr-user"></i> &nbsp; Username
            </label>
            <input   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="email" type="email" v-model="email" placeholder="Enter your email">
    </div>
   
    <div class="mb-4">
            <label class="block text-[white] text-sm font-bold mb-2 mt-5" for="username">
                <i class="fi fi-sr-user"></i> &nbsp; Password
            </label>
            <input   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="password" v-model="password" type="password" placeholder="******">
    </div>
   
   

    <div class="flex items-center justify-between">
            <button  @click.prevent="submitForm" class="btn bg-[#3fba3e] hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
              Sign In
            </button>
          
            <div class="text-center">
                <RouterLink  class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" to="/register">Sign up</RouterLink>
           </div>

          </div>
    </form>
</div>

</template>
  
<script>

import axios from 'axios';

import 'mosha-vue-toastify/dist/style.css';
 
 

  export default {


  data() {
    return {
     
      email:'',
      password:'',
      
    };
  },
  
  methods: {
    submitForm() {

      if( this.email != '' && this.password != ''){
     
      axios.post('https://pdf-scanner-puzphkwas-godfrey1234.vercel.app/login', {
       
        email: this.email,
        password : this.password
       
      })
      .then(response => {
        console.log(response.data.token);
        
        sessionStorage.setItem('token',response.data.token)
        this.$router.push('/landing')
       
       
        
      })
      .catch(error => {
        console.log(error);
      });
  
    }else{
      console.log('invalid login details');
    

    }
    }
  }
}

</script>

<style>
  .logo1{
    margin-top: -2%;
  }

  form{
    border-radius: 12px;
    box-shadow: 0 0px 65px #7f248d59;
  }

</style>
